version: 2
updates:
  - package-ecosystem: "npm"
    directory: "client/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "server/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "e2e/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
